// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SirketFiloTakip.Data;

#nullable disable

namespace SirketFiloTakip.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SirketFiloTakip.Models.Arac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AracTuru")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int>("GerekliEhliyetSinifi")
                        .HasColumnType("int");

                    b.Property<int>("Kilometre")
                        .HasColumnType("int");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModelYili")
                        .HasColumnType("int");

                    b.Property<string>("Plaka")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("YakitTuru")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Plaka")
                        .IsUnique();

                    b.ToTable("Araclar");
                });

            modelBuilder.Entity("SirketFiloTakip.Models.BakimKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AracId")
                        .HasColumnType("int");

                    b.Property<string>("BakimTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kilometre")
                        .HasColumnType("int");

                    b.Property<int?>("SonrakiBakimKm")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ToplamUcret")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AracId");

                    b.ToTable("BakimKayitlari");
                });

            modelBuilder.Entity("SirketFiloTakip.Models.Calisan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Ehliyet")
                        .HasColumnType("int");

                    b.Property<string>("Pozisyon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Calisanlar");
                });

            modelBuilder.Entity("SirketFiloTakip.Models.Gorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AracId")
                        .HasColumnType("int");

                    b.Property<int?>("BaslangicKm")
                        .HasColumnType("int");

                    b.Property<int?>("BitisKm")
                        .HasColumnType("int");

                    b.Property<int>("CalisanId")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GercekCikis")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GercekDonus")
                        .HasColumnType("datetime2");

                    b.Property<string>("KalkisYeri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PlanlananCikis")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlanlananDonus")
                        .HasColumnType("datetime2");

                    b.Property<string>("VarisYeri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AracId");

                    b.HasIndex("CalisanId");

                    b.ToTable("Gorevler");
                });

            modelBuilder.Entity("SirketFiloTakip.Models.HasarKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AracId")
                        .HasColumnType("int");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GorevId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Maliyet")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AracId");

                    b.HasIndex("GorevId");

                    b.ToTable("HasarKayitlari");
                });

            modelBuilder.Entity("SirketFiloTakip.Models.YakitKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AracId")
                        .HasColumnType("int");

                    b.Property<int>("Kilometre")
                        .HasColumnType("int");

                    b.Property<decimal>("Litre")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ToplamUcret")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("YakitTuru")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AracId");

                    b.ToTable("YakitKayitlari");
                });

            modelBuilder.Entity("SirketFiloTakip.Models.BakimKaydi", b =>
                {
                    b.HasOne("SirketFiloTakip.Models.Arac", "Arac")
                        .WithMany("BakimKayitlari")
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arac");
                });

            modelBuilder.Entity("SirketFiloTakip.Models.Gorev", b =>
                {
                    b.HasOne("SirketFiloTakip.Models.Arac", "Arac")
                        .WithMany("Gorevler")
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SirketFiloTakip.Models.Calisan", "Calisan")
                        .WithMany("Gorevler")
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arac");

                    b.Navigation("Calisan");
                });

            modelBuilder.Entity("SirketFiloTakip.Models.HasarKaydi", b =>
                {
                    b.HasOne("SirketFiloTakip.Models.Arac", "Arac")
                        .WithMany("HasarKayitlari")
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SirketFiloTakip.Models.Gorev", "Gorev")
                        .WithMany("HasarKayitlari")
                        .HasForeignKey("GorevId");

                    b.Navigation("Arac");

                    b.Navigation("Gorev");
                });

            modelBuilder.Entity("SirketFiloTakip.Models.YakitKaydi", b =>
                {
                    b.HasOne("SirketFiloTakip.Models.Arac", "Arac")
                        .WithMany("YakitKayitlari")
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arac");
                });

            modelBuilder.Entity("SirketFiloTakip.Models.Arac", b =>
                {
                    b.Navigation("BakimKayitlari");

                    b.Navigation("Gorevler");

                    b.Navigation("HasarKayitlari");

                    b.Navigation("YakitKayitlari");
                });

            modelBuilder.Entity("SirketFiloTakip.Models.Calisan", b =>
                {
                    b.Navigation("Gorevler");
                });

            modelBuilder.Entity("SirketFiloTakip.Models.Gorev", b =>
                {
                    b.Navigation("HasarKayitlari");
                });
#pragma warning restore 612, 618
        }
    }
}
